### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by NoszDom** [BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq#25]
#7 

Code duplication in these places:
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/blob/1f39494bb827bc1e7c688a5d8d4591dc342f62a2/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java#L471-L515

**Comment by bobarna** [comment]
Out of the project scope as discussed by the team.
