### ISSUE TITLE
Declare variables instead of calling getters multiple times

### ISSUE THREAD

**Issue by NoszDom** [BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq#26]
#7 

The results of getter functions should be saved in a local variable instead of repeatedly calling the getter function.

Examples:
- 1 attributes.getLength()
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/blob/1f39494bb827bc1e7c688a5d8d4591dc342f62a2/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java#L252-L253
- 2  node.getLocalName()
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/blob/1f39494bb827bc1e7c688a5d8d4591dc342f62a2/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java#L278-L279
- 3 objectType.getResource() and getURI()
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/blob/1f39494bb827bc1e7c688a5d8d4591dc342f62a2/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java#L311-L317
- 4 root.getNameSpace() node.getNameSpaceURI()
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/blob/1f39494bb827bc1e7c688a5d8d4591dc342f62a2/src/main/java/tr/com/srdc/ontmalizer/XML2OWLMapper.java#L377-L380

**Comment by bobarna** [comment]
Out of the project scope as discussed by the team.
