### ISSUE TITLE
Create and write IET-HF.md

### ISSUE THREAD

**Issue by bobarna** [BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq#5]
_A tárhely gyökérkönyvtárában egy IET-HF.md fájlban egy-két bekezdésben foglalja össze a csapat a saját szavaival, hogy mi a projekt célja, és nagyobb projekt esetén válasszon ki a funkcióknak egy részhalmazát, amivel később dolgozni fog majd._

**Comment by kurucz-gyuri** [comment]
WIP (see #17), but still needs references to the specific issues.
