### ISSUE TITLE
Manual code validation on a subset of the codebase

### ISSUE THREAD

**Issue by bobarna** [BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq#7]
_Manuális kód átvizsgálás elvégzése az alkalmazás egy részére (GitHub, Gerrit...) + Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarQube, SpotBugs, VS Code Analyzer, Codacy, Coverity Scan...)._

**Comment by bobarna** [comment]
_Mivel az eszközök rengeteg hibát és figyelmeztetést találhatnak, ezért elég azok egy részét megvizsgálni és ha a csapat minden tagja egyetért vele, akkor javítani. Törekedjetek arra, hogy különböző típusú, és lehetőleg nem triviális hibajelzéseket vizsgáljatok meg._

**Comment by bobarna** [comment]
As we discussed, @NoszDom will create new issues for subsets of codebases, marked for fixing/cleaning up.

**Comment by NoszDom** [comment]
- [x] Manual code validation
- [x] Fix the issues discovered during the manual code validation
- [x] Run a static analysis tool
- [x] Fix the issues discovered by the static analysis tool
